version: "3"

networks:
  front:
    ipam:
      config:
        - subnet: 10.0.0.0/16
  back:
    ipam:
      config:
        - subnet: 10.10.0.0/16

volumes:
  socket:
    driver: local
  log:
    driver: local
  docroot:
    driver: local

services:
  app:
    container_name: minimal_sns_app
    build: app/go
    volumes:
      - ./app/go:/app
    ports:
      - "1323:1323"
    networks:
      - front
      - back
    environment:
      TZ: "Asia/Tokyo"
  db:
    image: mysql:latest
    platform: linux/amd64
    container_name: db
    hostname: db
    networks:
      - back
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./mysql/0_init.sql:/docker-entrypoint-initdb.d/0_init.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: app
      TZ: "Asia/Tokyo"
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8001:8080"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ./api/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
  swagger-api:
    image: stoplight/prism:3
    container_name: "swagger-api"
    ports:
      - "8003:4010"
    command: mock -h 0.0.0.0 /openapi.yaml
    volumes:
      - ./api/openapi.yaml:/openapi.yaml
